package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ec.edu.sistemalicencias.model.entities.Usuario;
import ec.edu.sistemalicencias.model.exceptions.BaseDatosException;
import ec.edu.sistemalicencias.service.UsuarioService;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class ActualizarUsuarioView extends JFrame {
    private JPanel panelPrincipal;
    private JTextField txtIDABuscar;
    private JButton btnBuscar;
    private JTextField txtNombreCompletoActualizar;
    private JTextField txtUsernameActualizar;
    private JTextField txtPasswordActualizar;
    private JComboBox<String> cmbRolActualizar;
    private JButton btnActualizar;

    private final UsuarioService usuarioService;
    private Usuario usuarioEncontrado;

    public ActualizarUsuarioView() {
        this.usuarioService = new UsuarioService();
        setTitle("Actualización de Usuarios");
        setContentPane(panelPrincipal);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(700, 500);
        setLocationRelativeTo(null);

        configurarEstadoInicial();
        configurarListeners();
    }

    private void configurarEstadoInicial() {
        cmbRolActualizar.removeAllItems();
        cmbRolActualizar.addItem("ADMINISTRADOR");
        cmbRolActualizar.addItem("ANALISTA");

        setCamposEditables(false);
    }

    private void setCamposEditables(boolean estado) {
        txtNombreCompletoActualizar.setEnabled(estado);
        txtUsernameActualizar.setEnabled(estado);
        txtPasswordActualizar.setEnabled(estado);
        cmbRolActualizar.setEnabled(estado);
        btnActualizar.setEnabled(estado);
    }

    private void configurarListeners() {
        btnBuscar.addActionListener(e -> {
            try {
                String idStr = txtIDABuscar.getText().trim();
                if (idStr.isEmpty()) {
                    throw new BaseDatosException("Por favor, ingrese un ID para buscar.");
                }

                long id = Long.parseLong(idStr);
                usuarioEncontrado = usuarioService.obtenerUsuarioPorId(id);

                if (usuarioEncontrado != null) {
                    txtNombreCompletoActualizar.setText(usuarioEncontrado.getNombreCompleto());
                    txtUsernameActualizar.setText(usuarioEncontrado.getUsername());
                    txtPasswordActualizar.setText(usuarioEncontrado.getPasswordHash());
                    cmbRolActualizar.setSelectedItem(usuarioEncontrado.getRol());

                    setCamposEditables(true);
                    txtIDABuscar.setEnabled(false);
                    btnBuscar.setEnabled(false);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (BaseDatosException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Búsqueda", JOptionPane.WARNING_MESSAGE);
            }
        });

        btnActualizar.addActionListener(e -> {
            try {
                String nombre = txtNombreCompletoActualizar.getText().trim();
                String username = txtUsernameActualizar.getText().trim();
                String password = txtPasswordActualizar.getText().trim();

                if (nombre.isEmpty() || username.isEmpty() || password.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "Todos los campos deben estar llenos antes de guardar.",
                            "Campos Incompletos",
                            JOptionPane.WARNING_MESSAGE);
                    return; // Detenemos la ejecución aquí
                }

                usuarioEncontrado.setNombreCompleto(nombre);
                usuarioEncontrado.setUsername(username);
                usuarioEncontrado.setPasswordHash(password);
                usuarioEncontrado.setRol((String) cmbRolActualizar.getSelectedItem());

                usuarioService.modificarUsuario(usuarioEncontrado);

                JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (BaseDatosException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(15, 15, 15, 15), -1, -1));
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(7, 3, new Insets(25, 25, 25, 25), 20, 15));
        panel1.add(panelPrincipal, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        txtNombreCompletoActualizar = new JTextField();
        txtNombreCompletoActualizar.setText("");
        panelPrincipal.add(txtNombreCompletoActualizar, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtUsernameActualizar = new JTextField();
        txtUsernameActualizar.setText("");
        panelPrincipal.add(txtUsernameActualizar, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial", -1, 14, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Nombre Completo:");
        panelPrincipal.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial", -1, 14, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Username:");
        panelPrincipal.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Arial", -1, 14, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Password:");
        panelPrincipal.add(label3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$("Arial", -1, 14, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Selección de rol:");
        panelPrincipal.add(label4, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbRolActualizar = new JComboBox();
        cmbRolActualizar.setEditable(false);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("ADMIN");
        defaultComboBoxModel1.addElement("ANALISTA");
        cmbRolActualizar.setModel(defaultComboBoxModel1);
        panelPrincipal.add(cmbRolActualizar, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPasswordActualizar = new JTextField();
        panelPrincipal.add(txtPasswordActualizar, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$("Arial", -1, 22, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setText("ACTUALIZACIÓN DE USUARIOS - ADMINISTRADOR/ANALISTA");
        panelPrincipal.add(label5, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnActualizar = new JButton();
        btnActualizar.setText("ACTUALIZAR");
        panelPrincipal.add(btnActualizar, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$("Arial", -1, 14, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setText("ID a buscar:");
        panelPrincipal.add(label6, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtIDABuscar = new JTextField();
        txtIDABuscar.setText("");
        panelPrincipal.add(txtIDABuscar, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnBuscar = new JButton();
        btnBuscar.setText("BUSCAR");
        panelPrincipal.add(btnBuscar, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

}