package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ec.edu.sistemalicencias.service.UsuarioService;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Locale;

public class GestionUsuariosView extends JFrame {
    private JPanel panelPrincipal;
    private JButton btnRegistrarUsuario;
    private JButton btnActualizarDatos;
    private JButton btnMostrarUsuarios;
    private JButton btnCambiarEstadoUsuario;
    private JButton btnRegistrarLogs;
    private JButton btnSalir;
    private JButton btnIrMenuPrincipal;

    private final UsuarioService usuarioService;

    public GestionUsuariosView() {
        this.usuarioService = new UsuarioService();
        $$$setupUI$$$();

        setTitle("Panel de Administración - Gestión de Analistas");
        if (panelPrincipal != null) {
            setContentPane(panelPrincipal);
        }

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);
        configurarEventos();
    }

    private void configurarEventos() {
        btnSalir.addActionListener(e -> {
            this.dispose();
        });

        btnRegistrarUsuario.addActionListener(e -> {
            RegistrarUsuarioView ventanaRegistro = new RegistrarUsuarioView();
            ventanaRegistro.setVisible(true);
            ventanaRegistro.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    actualizarTablaSiExiste();
                }
            });
        });

        btnMostrarUsuarios.addActionListener(e -> {
            MostrarUsuariosView ventanaMostrar = new MostrarUsuariosView();
            ventanaMostrar.setVisible(true);
        });

        btnActualizarDatos.addActionListener(e -> {
            ActualizarUsuarioView vistaActualizar = new ActualizarUsuarioView();
            vistaActualizar.setVisible(true);
            vistaActualizar.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent windowEvent) {
                    actualizarTablaSiExiste();
                }
            });
        });

        btnCambiarEstadoUsuario.addActionListener(e -> {
            CambiarEstadoView vistaEstado = new CambiarEstadoView();
            vistaEstado.setVisible(true);
            vistaEstado.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent windowEvent) {
                    actualizarTablaSiExiste();
                }
            });
        });

        btnRegistrarLogs.addActionListener(e -> {
            MostrarLogsView vistaLogs = new MostrarLogsView();
            vistaLogs.setVisible(true);
        });

        btnIrMenuPrincipal.addActionListener(e -> {
            new MainView().setVisible(true);
            this.dispose();
        });
    }

    private void actualizarTablaSiExiste() {
        Window[] windows = Window.getWindows();
        for (Window window : windows) {
            if (window instanceof MostrarUsuariosView && window.isShowing()) {
                ((MostrarUsuariosView) window).cargarDatosTabla();
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(6, 3, new Insets(20, 20, 20, 20), 10, 15));
        panelPrincipal.setBorder(BorderFactory.createTitledBorder(null, "ADMINISTRACIÓN", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(20, 20, 20, 20), 10, 15));
        panelPrincipal.add(panel1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 20, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial", -1, 14, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Agencia Nacional de Tránsito");
        panel2.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial", Font.BOLD, 24, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-14121484));
        label2.setText("GESTIÓN DE USUARIOS - SISTEMA DE LICENCIAS ");
        panel2.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRegistrarUsuario = new JButton();
        Font btnRegistrarUsuarioFont = this.$$$getFont$$$("Arial", -1, 14, btnRegistrarUsuario.getFont());
        if (btnRegistrarUsuarioFont != null) btnRegistrarUsuario.setFont(btnRegistrarUsuarioFont);
        btnRegistrarUsuario.setText("Registrar Usuario");
        panelPrincipal.add(btnRegistrarUsuario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnActualizarDatos = new JButton();
        Font btnActualizarDatosFont = this.$$$getFont$$$("Arial", -1, 14, btnActualizarDatos.getFont());
        if (btnActualizarDatosFont != null) btnActualizarDatos.setFont(btnActualizarDatosFont);
        btnActualizarDatos.setText("Actualizar Datos de Usuarios");
        panelPrincipal.add(btnActualizarDatos, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnMostrarUsuarios = new JButton();
        Font btnMostrarUsuariosFont = this.$$$getFont$$$("Arial", -1, 14, btnMostrarUsuarios.getFont());
        if (btnMostrarUsuariosFont != null) btnMostrarUsuarios.setFont(btnMostrarUsuariosFont);
        btnMostrarUsuarios.setText("Mostrar Usuarios Registrados");
        panelPrincipal.add(btnMostrarUsuarios, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnCambiarEstadoUsuario = new JButton();
        Font btnCambiarEstadoUsuarioFont = this.$$$getFont$$$("Arial", -1, 14, btnCambiarEstadoUsuario.getFont());
        if (btnCambiarEstadoUsuarioFont != null) btnCambiarEstadoUsuario.setFont(btnCambiarEstadoUsuarioFont);
        btnCambiarEstadoUsuario.setText("Cambiar Estado / Eliminar");
        panelPrincipal.add(btnCambiarEstadoUsuario, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnRegistrarLogs = new JButton();
        Font btnRegistrarLogsFont = this.$$$getFont$$$("Arial", -1, 14, btnRegistrarLogs.getFont());
        if (btnRegistrarLogsFont != null) btnRegistrarLogs.setFont(btnRegistrarLogsFont);
        btnRegistrarLogs.setText("Historia de Logins (Logs)");
        panelPrincipal.add(btnRegistrarLogs, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnIrMenuPrincipal = new JButton();
        btnIrMenuPrincipal.setBackground(new Color(-14121484));
        Font btnIrMenuPrincipalFont = this.$$$getFont$$$("Arial", Font.BOLD, 14, btnIrMenuPrincipal.getFont());
        if (btnIrMenuPrincipalFont != null) btnIrMenuPrincipal.setFont(btnIrMenuPrincipalFont);
        btnIrMenuPrincipal.setForeground(new Color(-6248534));
        btnIrMenuPrincipal.setText("Ir al Menú de Licencias");
        panelPrincipal.add(btnIrMenuPrincipal, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 80), null, 0, false));
        btnSalir = new JButton();
        Font btnSalirFont = this.$$$getFont$$$("Arial", -1, 14, btnSalir.getFont());
        if (btnSalirFont != null) btnSalir.setFont(btnSalirFont);
        btnSalir.setText("CERRAR SESIÓN (LOGOUT)");
        panelPrincipal.add(btnSalir, new GridConstraints(4, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 50), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(20, 20, 20, 20), 10, 15));
        panelPrincipal.add(panel3, new GridConstraints(5, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 2, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Arial", -1, 10, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-6710887));
        label3.setText("Sistema de Licencias v2.0 - Desarrollado con Java y PostgreSQL");
        panel3.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }

}