package ec.edu.sistemalicencias.view;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.model.entities.Usuario;
import ec.edu.sistemalicencias.controller.UsuarioSesion;
import ec.edu.sistemalicencias.controller.LoginController;
import javax.swing.border.EmptyBorder;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class LoginView extends JFrame {
    private JPanel panelLogin;
    private JTextField txtUsuario;
    private JButton btnIngresar;
    private JPasswordField txtPassword;
    private LoginController loginController = new LoginController();


    public LoginView() {
        if (panelLogin == null) {
            panelLogin = new JPanel();
        }
        panelLogin.setBorder(new EmptyBorder(40, 40, 40, 40));
        setTitle("Sistema de Licencias de Conducir - Ecuador");
        setContentPane(panelLogin);
        setSize(400, 300);
        setMinimumSize(new Dimension(350, 300));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        btnIngresar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = txtUsuario.getText().trim();
                String password = new String(txtPassword.getPassword());

                // El login ya no dará error porque loginController ya existe
                Usuario usuario = loginController.login(username, password);

                if (usuario != null) {
                    UsuarioSesion.iniciarSesion(usuario);

                    // SIEMPRE ir al menú principal
                    new MainView().setVisible(true);

                    LoginView.this.dispose();
                }
            else {
                // 1. Mensaje de error
                JOptionPane.showMessageDialog(LoginView.this,
                        "Usuario o contraseña incorrectos. Por favor, intente de nuevo.",
                        "Error de Autenticación",
                        JOptionPane.ERROR_MESSAGE);

                // 2. Limpieza de campos
                txtUsuario.setText("");
                txtPassword.setText("");
                txtUsuario.requestFocus();
            }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelLogin = new JPanel();
        panelLogin.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        panelLogin.setForeground(new Color(-15066597));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Segoe UI", Font.BOLD, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("INICIAR SESION");
        panelLogin.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelLogin.add(spacer1, new GridConstraints(1, 2, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtUsuario = new JTextField();
        Font txtUsuarioFont = this.$$$getFont$$$("Consolas", Font.BOLD | Font.ITALIC, 14, txtUsuario.getFont());
        if (txtUsuarioFont != null) txtUsuario.setFont(txtUsuarioFont);
        txtUsuario.setForeground(new Color(-14671580));
        panelLogin.add(txtUsuario, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Segoe UI", Font.ITALIC, 12, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-10525848));
        label2.setText("Usuario:");
        panelLogin.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnIngresar = new JButton();
        Font btnIngresarFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnIngresar.getFont());
        if (btnIngresarFont != null) btnIngresar.setFont(btnIngresarFont);
        btnIngresar.setForeground(new Color(-16777216));
        btnIngresar.setHideActionText(false);
        btnIngresar.setText("Ingresar");
        panelLogin.add(btnIngresar, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Segoe UI", Font.ITALIC, 12, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-10525848));
        label3.setText("Contraseña:");
        panelLogin.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPassword = new JPasswordField();
        Font txtPasswordFont = this.$$$getFont$$$("Consolas", Font.BOLD | Font.ITALIC, 14, txtPassword.getFont());
        if (txtPasswordFont != null) txtPassword.setFont(txtPasswordFont);
        txtPassword.setForeground(new Color(-14671580));
        panelLogin.add(txtPassword, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelLogin;
    }

}
