package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ec.edu.sistemalicencias.model.entities.LoginRegistro;
import ec.edu.sistemalicencias.model.exceptions.BaseDatosException;
import ec.edu.sistemalicencias.service.LoginService;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class MostrarLogsView extends JFrame {
    private JPanel panelPrincipalLogs;
    private JTable tblLogs;
    private JButton btnCerrarLogs;

    private final LoginService loginService;

    public MostrarLogsView() {
        this.loginService = new LoginService();

        setTitle("Auditoría de Accesos al Sistema");
        setContentPane(panelPrincipalLogs);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(900, 550);
        setLocationRelativeTo(null);

        configurarTabla();
        cargarDatos();

        btnCerrarLogs.addActionListener(e -> dispose());
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("ID LOGIN");
        modelo.addColumn("ID USUARIO");
        modelo.addColumn("USERNAME");
        modelo.addColumn("FECHA Y HORA");

        tblLogs.setModel(modelo);
        tblLogs.getTableHeader().setReorderingAllowed(false);
        tblLogs.setRowHeight(25);
    }

    private void cargarDatos() {
        try {
            List<LoginRegistro> registros = loginService.obtenerHistorial();
            DefaultTableModel modelo = (DefaultTableModel) tblLogs.getModel();
            modelo.setRowCount(0);

            for (LoginRegistro reg : registros) {
                modelo.addRow(new Object[]{
                        reg.getIdLogin(),
                        reg.getIdUsuario(),
                        reg.getUsername(),
                        reg.getFechaIngreso()
                });
            }
        } catch (BaseDatosException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar auditoría: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipalLogs = new JPanel();
        panelPrincipalLogs.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 5, new Insets(10, 10, 10, 10), -1, -1));
        panelPrincipalLogs.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnCerrarLogs = new JButton();
        btnCerrarLogs.setText("CERRAR");
        panel1.add(btnCerrarLogs, new GridConstraints(2, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "Lista de Usuarios", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblLogs = new JTable();
        tblLogs.setFillsViewportHeight(true);
        scrollPane1.setViewportView(tblLogs);
        final JLabel label1 = new JLabel();
        label1.setText("HISTORIAL COMPLETO DE ACCESOS (ADMINS/ANALISTAS)");
        panel1.add(label1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipalLogs;
    }
}