package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ec.edu.sistemalicencias.model.entities.Usuario;
import ec.edu.sistemalicencias.service.UsuarioService;
import ec.edu.sistemalicencias.model.exceptions.BaseDatosException;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class MostrarUsuariosView extends JFrame {
    private JPanel panelPrincipal;
    private JTable tblUsuarios;
    private JButton btnCerrar;

    public MostrarUsuariosView() {
        $$$setupUI$$$();
        setTitle("Administración de Usuarios del Sistema");
        setContentPane(panelPrincipal);
        setSize(850, 550);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        personalizarTabla();
        cargarDatosTabla();

        btnCerrar.addActionListener(e -> dispose());
    }

    private void personalizarTabla() {
        tblUsuarios.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblUsuarios.setRowHeight(25);
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void cargarDatosTabla() {
        String[] columnas = {"ID", "Nombre Completo", "Username", "Rol", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            UsuarioService servicio = new UsuarioService();
            List<Usuario> lista = servicio.obtenerTodosLosUsuarios();

            for (Usuario u : lista) {
                Object[] fila = {
                        u.getId(),
                        u.getNombreCompleto(),
                        u.getUsername(),
                        u.getRol(),
                        u.isEstado() ? "Activo" : "Inactivo"
                };
                modelo.addRow(fila);
            }
            tblUsuarios.setModel(modelo);
        } catch (BaseDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btnCerrar = new JButton();
        btnCerrar.setText("CERRAR");
        panelPrincipal.add(btnCerrar, new GridConstraints(2, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelPrincipal.add(scrollPane1, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "Lista de Usuarios", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblUsuarios = new JTable();
        tblUsuarios.setFillsViewportHeight(true);
        scrollPane1.setViewportView(tblUsuarios);
        final JLabel label1 = new JLabel();
        label1.setText("SISTEMA DE GESTIÓN DE USUARIOS COMPLETO (ADMINS/ANALISTAS)");
        panelPrincipal.add(label1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }

}